title: 4mDigital
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5878136
  brandStrength: 0.7078853
  lightness: 0.6021807
  brandColors:
    - '#C5FAFF'
    - '#322E2D'
    - '#6F685E'
    - '#A4957E'
    - '#C5B8AF'
  rhythmicContrast: 0.5340502
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: 4mDigital
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.09318996
layout_spectrum: 0.9498208
