name: 4mDigital
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4551971
title: 4mDigital
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3038162
  lightness: 0.6021807
  saturation: 0.5878136
  rhythmicContrast: 0.5340502
purpose: []
